### ISSUE TITLE
Variables after an inline table get pulled into the table

### ISSUE THREAD

**Issue by zofrex** [ajwans/libtoml#11]
If I parse this toml and dump it (`echo $input | ./main -d`) it seems like the second table is getting added to the first:

```
name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
```

produces:

```
[name]
first = "Tom"
last = "Preston-Werner"
	[name.point]
	x = 1
	y = 2
```

But the following input (avoiding the inline tables feature):

```
[name]
first = "Tom"
last = "Preston-Werner"

[point]
x = 1
y = 2
```

Produces different output:

```
[name]
first = "Tom"
last = "Preston-Werner"

[point]
x = 1
y = 2
```

According to [the spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#inline-table) these should be equivalent.

**Comment by ajwans** [comment]
I believe these are fixed with my latest commits along with support for nested inline tables.
