### ISSUE TITLE
Safe iterators

### ISSUE THREAD

**Issue by halfwit** [ajwans/libtoml#14]
In Jansson, there's functions, json_array_foreach() and json_object_foreach(). Is there any future plans to implement such a thing into this lib? If not, in a few weeks I may be able to work towards implementing something of the such.

**Comment by ajwans** [comment]
The code already has something like this, the toml_walk function takes a toml_node_walker\* as an argument and executes the toml_node_walker at every node.  toml.c:toml_node_walker_free is an example of a walker function.

**Comment by halfwit** [comment]
Thanks! Will close, then.
