### ISSUE TITLE
TOML supported version

### ISSUE THREAD

**Issue by dkrikun** [ajwans/libtoml#6]
Does libtoml suppor TOML-0.4.0?
If not, is it planned?

**Comment by ajwans** [comment]
I just pushed some commits which make it close to passing all of burntsushi.

What exactly do you need?  There's still a little brokenness regarding arrays of tables.

**Comment by dkrikun** [comment]
There are many TOML parsers nowadays. Looking for the best one :smile_cat:

**Comment by ajwans** [comment]
Now supports v0.4.0.
